### ISSUE TITLE
Can nanomod take any control nanopore data as long as it is the same species?

### ISSUE THREAD

**Issue by JiahuiWangGit** [WGLab/NanoMod#12]
Hi, we have human native DNA sequenced from R9.4 pore but no control being sequenced/available matching these sample. Can nanomod take any control nanopore data as long as it is the same species?

**Comment by liuqianhn** [comment]
Hi @JiahuiWangGit , NanoMod can take the control data for native DNA of a certain species. It would be better to make the basecalling of control data and native DNA with a same tool. 
For human genome analysis, it would be better to analyze each chromosome separately rather than the whole genome so that there would not be memory issues.

**Comment by liuqianhn** [comment]
Closed due to no recent activities.
