### ISSUE TITLE
NanoMod Running error: Error information for different fast5 files: Resegment information for signal neighbors: 

### ISSUE THREAD

**Issue by JiahuiWangGit** [WGLab/NanoMod#9]
Hi,

I am trying to run NanoMod and got this error:

path_to_fast5s="/projects/li-lab/NanoCampare/albacore/output/workspace/pass/"
genome_fasta="/projects/li-lab/NanoCampare/Nanomod/methylation_example/reference.fasta"

 [wangj@helix180 Nanomod]$ python /projects/li-lab/software/NanoMod/bin/NanoMod.py Annotate --wrkBase1 $path_to_fast5s --Ref $genome_fasta
                  MinNumSignal: 4
                           Ref: /projects/li-lab/NanoCampare/Nanomod/methylation_example/reference.fasta
         Resegment_signal_wind: 4
                Resegment_wind: 4
                      alignStr: bwa
                   basecall_1d: Basecall_1D_000
              basecall_2strand: BaseCalled_template
              files_per_thread: 300
               kmer_model_file: None
                      outLevel: 2
                     recursive: 1
                       threads: 12
                      wrkBase1: /projects/li-lab/NanoCampare/albacore/output/workspace/pass/
/projects/li-lab/NanoCampare/albacore/output/workspace/pass/0/llssbzms2p35x_20161128_FNFAB45271_MN17073_sequencing_run_Hu_Bir_R94_1Dlig_fc5_92573_ch480_read1268_strand.fast5 499.0 57.0 0.0 1.0
/projects/li-lab/NanoCampare/albacore/output/workspace/pass/0/makeson_PC_20161117_FNFAB44989_MN17284_sequencing_run_MA_470_R9_4_NA12878_11_17_16_64834_ch263_read1176_strand.fast5 495.0 55.0 0.0 1.0
/projects/li-lab/NanoCampare/albacore/output/workspace/pass/0/LomanLabz_PC_20161128_FNFAF01253_MN17024_sequencing_run_20161128_Human_Qiagen_1D_R9_4_50330_ch500_read7919_strand.fast5 450.0 49.0 0.0 1.0
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -x ont2d -v 1 -t 1 /projects/li-lab/NanoCampare/Nanomod/methylation_example/reference.fasta /tmp/tmpwJ8VnD.fa
[main] Real time: 2.368 sec; CPU: 2.320 sec
handling - /projects/li-lab/NanoCampare/albacore/output/workspace/pass/0/LomanLabz_PC_20161128_FNFAF01253_MN17024_sequencing_run_20161128_Human_Qiagen_1D_R9_4_50330_ch500_read7919_strand.fast5
handling - /projects/li-lab/NanoCampare/albacore/output/workspace/pass/0/makeson_PC_20161117_FNFAB44989_MN17284_sequencing_run_MA_470_R9_4_NA12878_11_17_16_64834_ch263_read1176_strand.fast5
handling + /projects/li-lab/NanoCampare/albacore/output/workspace/pass/0/llssbzms2p35x_20161128_FNFAB45271_MN17073_sequencing_run_Hu_Bir_R94_1Dlig_fc5_92573_ch480_read1268_strand.fast5
Error information for different fast5 files:
Resegment information for signal neighbors: 
Total consuming time 16
`
If you have any idea what this error came from will be very helpful, thank you!

**Comment by liuqianhn** [comment]
Hi @JiahuiWangGit , Thank you for using our tool. 

If the error message you are referring to is the last third and last second line in your log file (that is "Error information for different fast5 files:" and "Resegment information for signal neighbors:"), your log file indicates there is no error. If there is error, the detail of the error will be output rather than the two simple lines. Sorry for this confusion. I think I might remove it.

If you are referring to something else, please upload the whole log file, since in the current log information, I do not see any error and your running is successful. Thank you.

**Comment by JiahuiWangGit** [comment]
Hi @liuqianhn, thank you for your quick response. Yes this is exactly the question I asked. 
Sorry for my misunderstanding in the log file, since there is no error in Annotate step, now I am moving to use the detect function.
A second question: is --wrkBase2 in detect function a required input? My dataset doesn't have a matched non-modified sample, can I use any tool to get a simulated version?

**Comment by liuqianhn** [comment]
Hi @JiahuiWangGit, I am afraid that "--wrkBase2" is necessary for NanoMod, since NanoMod needs to determine significant difference of modified bases. A simulated version of matched non-modified sample might be an option if real matched control samples are not available, but I did not test it and have no comment on it.  You are welcome to share your experience if you want to do that, which would greatly hep many others.  Thank you.
